# Generated by Django 6.0.5 on 2026-05-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BattalionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.TextField(blank=True, default='')),
                ('mission', models.TextField(blank=True, default='')),
                ('vision', models.TextField(blank=True, default='')),
                ('bb_object', models.TextField(blank=True, default='', verbose_name='BB Object Statement')),
                ('founded_year', models.PositiveIntegerField(blank=True, help_text='Four-digit year the battalion was established, e.g. 1985.', null=True)),
                ('headquarters', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Battalion Information',
                'verbose_name_plural': 'Battalion Information',
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='fas fa-star', help_text='Font Awesome class, e.g. "fas fa-heart", "fas fa-shield-alt", "fas fa-pray", "fas fa-users", "fas fa-bible".', max_length=80)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first in the values grid.')),
            ],
            options={
                'verbose_name': 'Core Value',
                'verbose_name_plural': 'Core Values',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LeadershipProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='leadership/')),
                ('bio', models.TextField(blank=True, default='')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first. Set 1 for the President.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this profile from the public About page.')),
            ],
            options={
                'verbose_name': 'Leadership Profile',
                'verbose_name_plural': 'Leadership Profiles',
                'ordering': ['order', 'name'],
            },
        ),
    ]
