# Generated by Django 6.0.5 on 2026-05-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, default='', help_text='Full postal address of the battalion headquarters.')),
                ('phone', models.CharField(blank=True, default='', help_text='Include country code, e.g. +234 800 000 0000', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('office_hours', models.CharField(blank=True, default='', help_text='e.g. "Mon – Fri: 9am – 5pm"', max_length=150)),
                ('facebook_url', models.URLField(blank=True, default='', verbose_name='Facebook URL')),
                ('instagram_url', models.URLField(blank=True, default='', verbose_name='Instagram URL')),
                ('whatsapp_number', models.CharField(blank=True, default='', help_text='Digits only, no + prefix, e.g. 2348000000000', max_length=30, verbose_name='WhatsApp Number')),
                ('map_embed_url', models.URLField(blank=True, default='', help_text='Paste the src URL from Google Maps → Share → Embed a map. Starts with https://www.google.com/maps/embed?', verbose_name='Google Maps Embed URL')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, help_text='Mark as read once the message has been actioned.')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
