# Generated by Django 6.0.5 on 2026-05-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactinfo_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='battalioninfo',
            name='active_companies',
            field=models.CharField(blank=True, default='12+', help_text='e.g. "12+" — shown in the stats strip.', max_length=20),
        ),
        migrations.AddField(
            model_name='battalioninfo',
            name='age_range',
            field=models.CharField(blank=True, default='Boys aged 5 – 18+', help_text='Age range of members, e.g. "Boys aged 5 – 18+".', max_length=100),
        ),
        migrations.AddField(
            model_name='battalioninfo',
            name='banner',
            field=models.ImageField(blank=True, help_text='Optional banner/hero image for the About page.', null=True, upload_to='battalion/'),
        ),
        migrations.AddField(
            model_name='battalioninfo',
            name='bb_sections',
            field=models.CharField(blank=True, default='4', help_text='Number of BB sections offered.', max_length=20),
        ),
        migrations.AddField(
            model_name='battalioninfo',
            name='boys_enrolled',
            field=models.CharField(blank=True, default='200+', help_text='e.g. "200+" — shown in the stats strip.', max_length=20),
        ),
        migrations.AddField(
            model_name='battalioninfo',
            name='cta_heading',
            field=models.CharField(blank=True, default='Get Involved with the Battalion', help_text='Heading for the bottom call-to-action section.', max_length=200),
        ),
        migrations.AddField(
            model_name='battalioninfo',
            name='cta_text',
            field=models.TextField(blank=True, default='Whether you want to enrol your son, start a new company in your church, or volunteer as an officer — we would love to hear from you.', help_text='Paragraph text beneath the CTA heading.'),
        ),
        migrations.AddField(
            model_name='battalioninfo',
            name='hero_title',
            field=models.CharField(blank=True, default='About Unity Battalion', help_text='H1 heading on the About page hero banner.', max_length=200),
        ),
        migrations.AddField(
            model_name='battalioninfo',
            name='history_heading',
            field=models.CharField(blank=True, default='A Legacy of Faith & Service', help_text='H2 heading for the History section.', max_length=200),
        ),
        migrations.AddField(
            model_name='battalioninfo',
            name='motto',
            field=models.CharField(blank=True, default='Sure and Stedfast', help_text='Official motto, e.g. "Sure and Stedfast".', max_length=200),
        ),
        migrations.AddField(
            model_name='battalioninfo',
            name='name',
            field=models.CharField(blank=True, default='Unity Battalion Council', help_text='Full name of the battalion council.', max_length=200),
        ),
        migrations.AddField(
            model_name='battalioninfo',
            name='organisation',
            field=models.CharField(blank=True, default="Boys' Brigade Nigeria", help_text='Parent organisation name, e.g. "Boys\' Brigade Nigeria".', max_length=200),
        ),
        migrations.AddField(
            model_name='battalioninfo',
            name='subtitle',
            field=models.CharField(blank=True, default='Boys Brigade Council', help_text='Short subtitle shown beneath the name, e.g. "Boys Brigade Council".', max_length=200),
        ),
    ]
