# Generated by Django 6.0.5 on 2026-06-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_battalioninfo_active_companies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battalioninfo',
            name='gallery_subtitle',
            field=models.TextField(blank=True, default='A glimpse into the life of Unity Battalion — parades, competitions, training camps, and community service captured in pictures.', help_text='Subtitle for the gallery preview section on the home page.'),
        ),
        migrations.AddField(
            model_name='battalioninfo',
            name='home_cta_heading',
            field=models.TextField(blank=True, default='Ready to Join the Battalion?', help_text='Heading for the CTA banner at the bottom of the home page.'),
        ),
        migrations.AddField(
            model_name='battalioninfo',
            name='home_cta_text',
            field=models.TextField(blank=True, default="Whether you're a parent looking for the right programme for your boy, or a church wanting to start a company, we'd love to hear from you.", help_text='Paragraph text beneath the home page CTA heading.'),
        ),
        migrations.AddField(
            model_name='battalioninfo',
            name='home_hero_description',
            field=models.TextField(blank=True, default="Unity Battalion Council is committed to advancing Christ's Kingdom among boys — nurturing obedience, reverence, discipline, self-respect and all that tends towards a true Christian manliness.", help_text='Short paragraph beneath the hero heading on the home page.'),
        ),
        migrations.AddField(
            model_name='battalioninfo',
            name='home_hero_title',
            field=models.TextField(blank=True, default='Building Boys of Character, Faith & Service', help_text='Main H1 heading on the home page hero section.'),
        ),
        migrations.AddField(
            model_name='battalioninfo',
            name='years_of_service',
            field=models.CharField(blank=True, default='10+', help_text='e.g. "10+" — shown as the "Years of Service" stat on the home page.', max_length=20),
        ),
    ]
