# Generated by Django 6.0.5 on 2026-06-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_battalioninfo_gallery_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battalioninfo',
            name='cta_text',
            field=models.TextField(blank=True, default='Whether you want to enrol your son, start a new company in your church, or volunteer as an officer, we would love to hear from you.', help_text='Paragraph text beneath the CTA heading.'),
        ),
        migrations.AlterField(
            model_name='battalioninfo',
            name='gallery_subtitle',
            field=models.TextField(blank=True, default='A glimpse into the life of Unity Battalion: parades, competitions, training camps, and community service captured in pictures.', help_text='Subtitle for the gallery preview section on the home page.'),
        ),
        migrations.AlterField(
            model_name='battalioninfo',
            name='home_hero_description',
            field=models.TextField(blank=True, default="Unity Battalion Council is committed to advancing Christ's Kingdom among boys, nurturing obedience, reverence, discipline, self-respect and all that tends towards a true Christian manliness.", help_text='Short paragraph beneath the hero heading on the home page.'),
        ),
    ]
