# Generated by Django 6.0.5 on 2026-09-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_battalioninfo_cta_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battalioninfo',
            name='announcements_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='battalioninfo',
            name='announcements_text',
            field=models.TextField(default='Welcome to Unity Battalion Council - Boys Brigade • Annual Battalion Inspection - Save the Date • Register your company for the new season • "Sure and Stedfast" - The Boys Brigade Motto • Building Boys for Life since 1883'),
        ),
        migrations.AddField(
            model_name='battalioninfo',
            name='contact_intro_text',
            field=models.TextField(blank=True, default='Have a question, want to register a company, or learn more about Unity Battalion? We would love to hear from you.'),
        ),
        migrations.AddField(
            model_name='battalioninfo',
            name='footer_copyright_text',
            field=models.CharField(default='Unity Battalion Council, Boys Brigade.', max_length=200),
        ),
        migrations.AddField(
            model_name='battalioninfo',
            name='hero_bg_image',
            field=models.ImageField(blank=True, help_text='Background image for the home page hero section', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='battalioninfo',
            name='seo_description',
            field=models.TextField(blank=True, default='Unity Battalion Council, Boys Brigade Nigeria. Sure and Stedfast.'),
        ),
        migrations.AddField(
            model_name='battalioninfo',
            name='seo_title',
            field=models.CharField(blank=True, default='Unity Battalion Council - Boys Brigade Nigeria', max_length=200),
        ),
        migrations.AddField(
            model_name='battalioninfo',
            name='show_about_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='battalioninfo',
            name='show_events_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='battalioninfo',
            name='show_gallery_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='battalioninfo',
            name='show_stats_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='battalioninfo',
            name='site_name',
            field=models.CharField(default='Unity Battalion', max_length=200),
        ),
        migrations.AddField(
            model_name='battalioninfo',
            name='site_tagline',
            field=models.CharField(default='Boys Brigade Council', max_length=200),
        ),
    ]
